// Wiki-as-markdown export.
//
// Takes the live wiki (topics + memories + curated articles + installed packs)
// and serialises it as a folder of .md files — one per topic, plus an index
// and a README. Bundled into a .zip the user can:
//   - unzip and open in Obsidian (wikilinks just work)
//   - push to a git repo for version history
//   - share with a colleague (no Clude account required to read)
//
// Each file carries enough YAML frontmatter to be re-importable into a
// Clude instance without losing topic/cluster/source attribution.

import JSZip from 'jszip';
import type { Memory } from '../types/memory';
import type { Topic } from '../pages/Wiki/wiki-data';
import type { TopicArticle, ArticleSection, ProseBlock } from '../pages/Wiki/use-topic-article';
import type { MemoryPack } from '../pages/Wiki/wiki-packs';

interface BuildWikiOpts {
  topics: Topic[];
  memories: Memory[];
  buildArticle: (topic: Topic) => TopicArticle | null;
  installedPacks: MemoryPack[];
  workspaceName: string;
}

/** Build a Blob containing the wiki .zip — caller triggers download. */
export async function buildWikiZip(opts: BuildWikiOpts): Promise<Blob> {
  const zip = new JSZip();
  const wiki = zip.folder('wiki')!;
  const exportedAt = new Date().toISOString();

  zip.file('README.md', readmeMarkdown(opts, exportedAt));

  // One file per topic, slugified.
  const topicFiles: { topic: Topic; filename: string; article: TopicArticle | null }[] = [];
  for (const topic of opts.topics) {
    const article = opts.buildArticle(topic);
    const filename = `${slug(topic.id)}.md`;
    topicFiles.push({ topic, filename, article });
    wiki.file(filename, articleToMarkdown(topic, article, exportedAt));
  }

  zip.file('index.md', indexMarkdown(topicFiles, exportedAt));
  zip.file('packs.md', packsMarkdown(opts.installedPacks, exportedAt));

  return await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
}

/** Trigger browser download of a generated zip. */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─────────── README ───────────

function readmeMarkdown(opts: BuildWikiOpts, exportedAt: string): string {
  return `# ${escapeMd(opts.workspaceName)} — Brain Wiki

This folder is a snapshot of your Clude Brain Wiki. Open it in any
markdown editor — Obsidian works particularly well because the wikilinks
\`[[topic-id]]\` resolve as native cross-references.

## Contents

- **\`index.md\`** — catalogue of every topic with a one-line summary
- **\`wiki/*.md\`** — one file per topic with the full article
- **\`packs.md\`** — which memory packs your wiki uses + their auto-categorisation rules

## Editing

Edits made here are NOT synced back automatically. To re-import after
editing, use \`clude import\` (CLI) or paste into the dashboard's import flow.

## Provenance

Every article carries YAML frontmatter with topic id, cluster, and the
hash IDs of the source memories. You can verify any source against your
on-chain anchors by looking up the hash on Solana.

## Snapshot info

- **Exported**: ${exportedAt}
- **Topics**: ${opts.topics.length}
- **Memories referenced**: ${opts.memories.length}
- **Installed packs**: ${opts.installedPacks.map((p) => p.name).join(', ')}

---

*Generated by Clude. https://clude.io*
`;
}

// ─────────── Index ───────────

function indexMarkdown(
  files: { topic: Topic; filename: string; article: TopicArticle | null }[],
  exportedAt: string,
): string {
  const lines: string[] = [
    '---',
    'title: Index',
    `exported_at: ${exportedAt}`,
    'kind: wiki-index',
    '---',
    '',
    '# Index',
    '',
    'Catalogue of every topic in this wiki. Click any link to open.',
    '',
  ];

  // Group by cluster so the catalogue reads as sections.
  const grouped = new Map<string, typeof files>();
  for (const f of files) {
    const cluster = f.topic.cluster ?? 'other';
    if (!grouped.has(cluster)) grouped.set(cluster, []);
    grouped.get(cluster)!.push(f);
  }

  for (const [cluster, items] of grouped) {
    lines.push(`## ${capitalize(cluster)}`, '');
    for (const { topic, filename, article } of items) {
      const summary = article?.lede ?? topic.summary ?? '';
      const meta = article?.meta;
      lines.push(`- [${escapeMd(topic.name)}](wiki/${filename})${meta ? ` — *${meta.sources} ${meta.sources === 1 ? 'note' : 'notes'} · updated ${meta.updated}*` : ''}`);
      if (summary) lines.push(`  > ${escapeMd(summary)}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─────────── Packs page ───────────

function packsMarkdown(packs: MemoryPack[], exportedAt: string): string {
  const lines: string[] = [
    '---',
    'title: Memory Packs',
    `exported_at: ${exportedAt}`,
    'kind: packs-index',
    '---',
    '',
    '# Memory Packs',
    '',
    'These are the topic-taxonomy packs installed on this wiki. Each declares topics, section templates, and the keyword rules that auto-categorise incoming memories.',
    '',
  ];

  for (const pack of packs) {
    lines.push(`## ${escapeMd(pack.name)}`);
    lines.push('');
    lines.push(`**${escapeMd(pack.vendor)} · ${escapeMd(pack.vertical)} · v${escapeMd(pack.version)}**`);
    lines.push('');
    lines.push(escapeMd(pack.description));
    lines.push('');
    lines.push('### Topics');
    lines.push('');
    for (const t of pack.topics) {
      lines.push(`- **${escapeMd(t.name)}** — ${escapeMd(t.summary)}`);
    }
    lines.push('');
    lines.push('### Auto-categorisation rules');
    lines.push('');
    for (const r of pack.rules) {
      lines.push(`- \`${r.topicId}\`: ${r.keywords.map((k) => `\`${k}\``).join(', ')}${r.excludeKeywords && r.excludeKeywords.length > 0 ? ` (except: ${r.excludeKeywords.map((k) => `\`${k}\``).join(', ')})` : ''}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─────────── Article (per topic) ───────────

function articleToMarkdown(topic: Topic, article: TopicArticle | null, exportedAt: string): string {
  const lines: string[] = [];

  // Frontmatter — enough to round-trip the topic identity + provenance.
  lines.push('---');
  lines.push(`title: ${jsonString(topic.name)}`);
  lines.push(`topic_id: ${topic.id}`);
  lines.push(`cluster: ${topic.cluster}`);
  lines.push(`color: '${topic.color}'`);
  lines.push(`exported_at: ${exportedAt}`);
  if (article?.meta) {
    lines.push(`source_count: ${article.meta.sources}`);
    lines.push(`last_updated: ${jsonString(article.meta.updated)}`);
    lines.push(`confidence: ${article.meta.confidence}`);
  }
  // Collect every memory hash referenced anywhere in the article.
  const sources = collectSourceHashes(article);
  if (sources.length > 0) {
    lines.push('sources:');
    for (const s of sources) lines.push(`  - ${s}`);
  }
  lines.push('---');
  lines.push('');

  lines.push(`# ${escapeMd(topic.name)}`);
  lines.push('');
  if (topic.summary) {
    lines.push(`> *${escapeMd(topic.summary)}*`);
    lines.push('');
  }

  if (!article || article.sections.length === 0) {
    lines.push('*Empty topic — nothing tracked here yet.*');
    return lines.join('\n');
  }

  for (const section of article.sections) {
    sectionToMarkdown(section, lines);
  }

  return lines.join('\n');
}

function sectionToMarkdown(section: ArticleSection, lines: string[]): void {
  const kindBadge = section.kind && section.kind !== 'overview' ? ` _[${section.kind}]_` : '';
  lines.push(`## ${escapeMd(section.title)}${kindBadge}`);
  lines.push('');

  if (section.prose && section.prose.length > 0) {
    for (const block of section.prose) {
      proseBlockToMarkdown(block, section.memories, lines);
    }
  } else {
    for (const m of section.memories) {
      memoryToMarkdown(m, lines);
    }
  }
}

function proseBlockToMarkdown(block: ProseBlock, memories: Memory[], lines: string[]): void {
  if (block.kind === 'p') {
    lines.push(unwrapInline(block.text));
    lines.push('');
    return;
  }
  if (block.kind === 'callout') {
    const tag = block.tone === 'question' ? '❓ Open question' : '📝 Note';
    lines.push(`> **${tag}** — ${unwrapInline(block.text)}`);
    lines.push('');
    return;
  }
  if (block.kind === 'list') {
    for (const item of block.items) {
      lines.push(`- ${unwrapInline(item)}`);
    }
    lines.push('');
    return;
  }
  if (block.kind === 'code') {
    lines.push(`\`\`\`${block.lang ?? ''}`);
    lines.push(block.text);
    lines.push('```');
    lines.push('');
    return;
  }
  if (block.kind === 'reframe') {
    const memory = memories.find((m) => m.hash_id === block.memoryHash);
    if (memory) memoryToMarkdown(memory, lines);
    return;
  }
  if (block.kind === 'contradiction') {
    lines.push('> ⚠ **Contradiction detected** — see the dashboard for the disagreeing memory pair and resolution options.');
    lines.push('');
    return;
  }
  if (block.kind === 'placeholder') {
    lines.push(`*Empty — your agent will populate this section as it captures relevant memories.*`);
    if (block.hintKeywords && block.hintKeywords.length > 0) {
      lines.push('');
      lines.push(`*Auto-tagged on: ${block.hintKeywords.map((k) => `\`${k}\``).join(', ')}*`);
    }
    lines.push('');
    return;
  }
}

function memoryToMarkdown(memory: Memory, lines: string[]): void {
  const reframed = memory.summary && memory.summary !== memory.content;
  if (reframed) {
    lines.push(`> ${escapeMd(memory.summary)}`);
    lines.push(`> `);
    lines.push(`> *— from your ${escapeMd(memory.source)} · ${formatDate(memory.created_at)} · \`${memory.hash_id}\`*`);
    lines.push('');
    lines.push('<details><summary>Original</summary>');
    lines.push('');
    lines.push(escapeMd(memory.content));
    lines.push('');
    lines.push('</details>');
    lines.push('');
  } else {
    lines.push(escapeMd(memory.content));
    lines.push(`*— from your ${escapeMd(memory.source)} · ${formatDate(memory.created_at)} · \`${memory.hash_id}\`*`);
    lines.push('');
  }
}

// ─────────── Inline conversion ───────────
//
// Our prose uses [[topic-id|label]] for wikilinks (which Obsidian also
// recognises) and **bold** / *italic* / `code` / `0.93⁷` MathJax-ish
// inline conventions. Most of these are already markdown-compatible.
// We convert wikilinks to Obsidian-friendly form: [[label]] when the
// target slug equals the label (Obsidian won't show the slug if it
// doesn't have a target), or [[topic-id|label]] otherwise.
function unwrapInline(text: string): string {
  // Already markdown for **bold**, *italic*, `code`. Wikilinks are already
  // Obsidian-compatible (we use the same syntax). No escaping needed.
  return text;
}

// ─────────── Helpers ───────────

function collectSourceHashes(article: TopicArticle | null): string[] {
  if (!article) return [];
  const hashes = new Set<string>();
  for (const section of article.sections) {
    for (const m of section.memories) {
      if (m.hash_id) hashes.add(m.hash_id);
    }
    if (section.prose) {
      for (const b of section.prose) {
        if (b.kind === 'reframe') hashes.add(b.memoryHash);
      }
    }
  }
  return Array.from(hashes);
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '');
}

function escapeMd(s: string): string {
  return (s ?? '').replace(/\\/g, '\\\\');
}

function jsonString(s: string): string {
  return JSON.stringify(s);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function formatDate(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toISOString().slice(0, 10);
  } catch {
    return iso;
  }
}
